@startuml 

legend
|= Color |= Type |= Meaning |
|<back:lightblue>           | App Specific | Components specific to the application, containing the main logic.|
|<back:lightgreen>           | Common       | Generic, reusable components across different applications.|
endlegend

package Project_Package
{
    class MainCpp #lightblue {}
    class RtosTask<<abstract>> #lightgreen {}
    class Node<<abstract>> #lightgreen {}

    'Master Node 
    package MasterNode_Package 
    {
        class MasterNode <<Node>> #lightblue {}
        
        class MasterBridge <<RtosTask>> #lightgreen {}
        MasterNode *-- MasterBridge

        note bottom of MasterBridge
            Remote Proxy
            Design Pattern 
        end note

        class MasterTask <<RtosTask>> #lightblue {}

        MasterNode *-- MasterTask

        MasterNode *-- WebServerTask

        class WebServerTask <<RtosTask>> #lightblue {}
        MasterTask <--> WebServerTask

        class _Application_Task <<RtosTask>> #lightblue {}
        note bottom of _Application_Task
            Placeholder for 
            application 
            specific 
            task(s)
        end note
        MasterNode *-- _Application_Task
        MasterTask <--> _Application_Task
        
        class ApiServer #lightblue {}
        WebServerTask *-- ApiServer
    }

    MainCpp *-- MasterNode

    'Slave Node
    package SlaveNode_Package
    {
        class SlaveBridge <<RtosTask>> #lightgreen {}
        note bottom of SlaveBridge
            Remote Proxy
            Design Pattern 
        end note

        class SlaveNode <<Node>> #lightgreen {}

        SlaveNode *-- SlaveBridge

        ' Slave Task
        class SlaveTask <<RtosTask>> #lightgreen {}
        SlaveNode *-- SlaveTask
    }

    MainCpp *-- "0..*"SlaveNode

    MasterBridge .. SlaveBridge : Direct or \n ESP-NOW

    package ServiceTasks_Package 
    {
        class ServiceTask <<abstract, RtosTask>> #lightgreen {}

        class ServiceTasks #lightgreen {}
        class MasterServiceTasks #lightgreen {}
        class SlaveServiceTasks #lightgreen {}

        MasterServiceTasks --|> ServiceTasks
        SlaveServiceTasks --|> ServiceTasks

        class LoggingTask <<ServiceTask>> #lightgreen {}
        class StatusTask <<ServiceTask>> #lightgreen {}
        class OtaTask <<ServiceTask>> #lightgreen {}

        LoggingTask --|> ServiceTask
        StatusTask --|> ServiceTask
        OtaTask --|> ServiceTask

        MasterServiceTasks *-- StatusTask
        ServiceTasks *-- LoggingTask
        ServiceTasks *-- OtaTask
    }

    package FunctionTasks_Package
    {
        class FunctionTasks #lightgreen {}
    }

    MasterNode *-- "0..*" FunctionTasks
    SlaveNode  *-- "1..*" FunctionTasks
    MasterTask <-> MasterBridge

    MasterNode *---- MasterServiceTasks
    SlaveNode *---- SlaveServiceTasks
    SlaveTask <-> SlaveBridge
}

@enduml

@startuml 

legend
|= Color |= Type |= Meaning |
|<back:lightblue>           | App Specific | Components specific to the application, containing the main logic.|
|<back:lightgreen>           | Common       | Generic, reusable components across different applications.|
endlegend

title Api 

package MasterNode_Package
{
    class ApiServer #lightblue {}
    WebServerTask *-- ApiServer

    class ControlApi #lightblue {}
    ApiServer *-- ControlApi
    class PresetEditApi #lightblue {}
    note bottom of PresetEditApi
        Specific for one project
    end note
    ApiServer *-- PresetEditApi
    class ConfigurationApi #lightblue {}
    ApiServer *-- ConfigurationApi

    class ServiceApiServer #lightgreen {}
    ApiServer *-- ServiceApiServer
    class StatusApi #lightgreen {}
    ServiceApiServer *-- StatusApi
    class OtaApi #lightgreen {}
    ServiceApiServer *-- OtaApi
    class LoggingApi #lightgreen {}
    ServiceApiServer *-- LoggingApi
}

@enduml 

@startuml 

legend
|= Color |= Type |= Meaning |
|<back:lightblue>           | App Specific | Components specific to the application, containing the main logic.|
|<back:lightgreen>           | Common       | Generic, reusable components across different applications.|
endlegend

title Function Tasks

package FunctionTasks_Package
{
    class FunctionTask<<abstract, RtosTask>> #lightgreen {}

    class FunctionTasks #lightgreen {}
    
    class InputPinsTask #lightgreen {}
    InputPinsTask --|> FunctionTask
    
    class AnalogInputPinsTask #lightgreen {}
    AnalogInputPinsTask --|> InputPinsTask
    class SingleAnalogInputPinTask #lightgreen {}
    SingleAnalogInputPinTask --|> AnalogInputPinsTask
    class AnalogInputChannel #lightgreen {}
    SingleAnalogInputPinTask *-- "0..*" AnalogInputChannel

    class DigitalInputPinsTask #lightgreen {}
    DigitalInputPinsTask --|> InputPinsTask
    class SingleDigitalInputPinTask #lightgreen {}
    SingleDigitalInputPinTask --|> DigitalInputPinsTask
    class ShiftRegisterInputPinsTask #lightgreen {}
    ShiftRegisterInputPinsTask --|> DigitalInputPinsTask
    class DigitalInputChannel #lightgreen {}
    SingleDigitalInputPinTask *-- "1" DigitalInputChannel
    ShiftRegisterInputPinsTask *-- "0..64" DigitalInputChannel

    class DigitalOutputPinsTask #lightgreen {}
    DigitalOutputPinsTask --|> FunctionTask
    class SingleDigitalOutputPinTask #lightgreen {}
    SingleDigitalOutputPinTask --|> DigitalOutputPinsTask
    class ShiftRegisterOutputPinsTask #lightgreen {}
    ShiftRegisterOutputPinsTask --|> DigitalOutputPinsTask
    class DigitalOutputChannel #lightgreen {}
    SingleDigitalOutputPinTask *-- "1" DigitalOutputChannel
    ShiftRegisterOutputPinsTask *-- "0..64" DigitalOutputChannel
    
    class InputOutputPinsTask #lightgreen {}
    InputOutputPinsTask --|> FunctionTask
    class ShiftRegisterInputOutputPinsTask #lightgreen {}
    ShiftRegisterInputOutputPinsTask --|> InputOutputPinsTask
    class Mcp23017InputOutputPinsTask #lightgreen {}
    Mcp23017InputOutputPinsTask --|> InputOutputPinsTask
    DigitalInputChannel *-- "0..64" ShiftRegisterInputOutputPinsTask
    DigitalOutputChannel *-- "0..64" ShiftRegisterInputOutputPinsTask
    DigitalInputChannel *-- "0..64" Mcp23017InputOutputPinsTask
    DigitalOutputChannel *-- "0..64" Mcp23017InputOutputPinsTask

    class LedSegmentsTask #lightgreen {}
    LedSegmentsTask --|> FunctionTask
    class IcLessSegmentsTask #lightgreen {}
    IcLessSegmentsTask --|> LedSegmentsTask
    class Tm1637SegmentTask #lightgreen {}
    Tm1637SegmentTask --|> LedSegmentsTask
    class Max7219SegmentTask #lightgreen {}
    Max7219SegmentTask --|> LedSegmentsTask
    IcLessSegmentsTask *-- "0..64" DigitalOutputChannel
    Tm1637SegmentTask *-- "0..64" DigitalOutputChannel
    Max7219SegmentTask *-- "0..64" DigitalOutputChannel
    
    class LedStripsTask #lightgreen {}
    LedStripsTask --|> FunctionTask
    class Ws2811StripTask #lightgreen {}
    Ws2811StripTask --|> LedStripsTask
    class Ws2812bStripTask #lightgreen {}
    Ws2812bStripTask --|> LedStripsTask
    class Ws2813StripTask #lightgreen {}
    Ws2813StripTask --|> LedStripsTask

    class DmxMax3485Task #lightgreen {}
    DmxMax3485Task --|> FunctionTask

    class MidiTask #lightgreen {}
    MidiTask --|> FunctionTask

    class RelaisTask #lightgreen {}
    RelaisTask --|> FunctionTask
    class RelaisChannel #lightgreen {}
    RelaisTask *-- "0..8" RelaisChannel

    class GasSensorTask #lightgreen {}
    GasSensorTask --|> FunctionTask
    
    FunctionTasks *- "0..*"FunctionTask
}

@enduml 

@startuml 

@startuml

actor User 

User -> Website : Access website
Website -> WebServerTask: HTTP Request
WebServerTask -> ApiServer: Handle HTTP Request 
ApiServer ->    XXXApi: Handle control API request
XXXApi -> MasterTask: Request action
MasterTask -> MasterBridge: Send message
alt local message, master task
MasterBridge -> MasterTask: Handle message
MasterTask -> MasterBridge: Return result
else local message, service task 
MasterBridge -> ServiceTasks: Handle message
ServiceTasks -> MasterBridge: Return result
else local message, function task 
MasterBridge -> FunctionTask: Handle message
FunctionTask -> MasterBridge: Return result
else remote message
MasterBridge -> SlaveBridge: Send message via ESP-NOW
alt message for slave task
SlaveBridge -> SlaveBridge: Handle message
SlaveTask -> SlaveBridge: Return result
else message for service task
SlaveBridge -> ServiceTasks: Handle message
ServiceTasks -> SlaveBridge: Return result
else message for function task   
SlaveBridge -> FunctionTask: Handle message
FunctionTask -> SlaveBridge: Return result
end
else error message
SlaveBridge -> MasterBridge: Return 
end
MasterBridge -> MasterTask: Return result
MasterTask -> WebServerTask: Return HTTP Response
WebServerTask -> Website: Show

@enduml

