@startuml 

legend
|= Color |= Type |= Meaning |
|<back:lightblue>           | App Specific | Components specific to the application, containing the main logic.|
|<back:lightgreen>           | Common       | Generic, reusable components across different applications.|
endlegend

class MainCpp #lightblue {}
class RtosTask<<abstract>> #lightgreen {}
class Node<<abstract>> #lightgreen {}

'Master Node 
package MasterNode_Package 
{
    class MasterNode <<Node>> #lightblue {}
    
    class MasterBridge <<RtosTask>> #lightgreen {}
    MasterNode *-- MasterBridge

    note bottom of MasterBridge
        Remote Proxy
        Design Pattern 
    end note

    class MasterTask <<RtosTask>> #lightblue {}

    MasterNode *-- MasterTask

    MasterNode *-- WebserverTask

    class WebserverTask <<RtosTask>> #lightblue {}
    MasterTask <--> WebserverTask

    class PresetsTask <<RtosTask>> #lightblue {}
    MasterNode *-- PresetsTask
    MasterTask <--> PresetsTask
    
    class ApiServer #lightblue {}
    WebserverTask *-- ApiServer

    class ControlApi #lightblue {}
    ApiServer *-- ControlApi
    class PresetEditApi #lightblue {}
    note bottom of PresetEditApi
        Specific for one project
    end note
    ApiServer *-- PresetEditApi
    class ConfigurationApi #lightblue {}
    ApiServer *-- ConfigurationApi

    class ServiceApiServer #lightgreen {}
    ApiServer *-- ServiceApiServer
    class StatusApi #lightgreen {}
    ServiceApiServer *-- StatusApi
    class OtaApi #lightgreen {}
    ServiceApiServer *-- OtaApi
    class LoggingApi #lightgreen {}
    ServiceApiServer *-- LoggingApi
}

MainCpp *-- MasterNode

'Slave Node
package SlaveNode_Package
{
    class SlaveBridge <<RtosTask>> #lightgreen {}
    note bottom of SlaveBridge
        Remote Proxy
        Design Pattern 
    end note

    class SlaveNode <<Node>> #lightgreen {}

    SlaveNode *-- SlaveBridge

    ' Slave Task
    class SlaveTask <<RtosTask>> #lightgreen {}
    SlaveNode *-- SlaveTask
}

MainCpp *-- SlaveNode

MasterBridge .. SlaveBridge : Direct or \n ESP-NOW

package ServiceTasksPackage 
{
    class ServiceTasks #lightgreen {}
    
    class LoggingTask <<RtosTask>> #lightgreen {}
    class StatusTask <<RtosTask>> #lightgreen {}
    class OtaTask <<RtosTask>> #lightgreen {}

    ServiceTasks *-- LoggingTask
    ServiceTasks *-- StatusTask
    ServiceTasks *-- OtaTask
}


package SubTasksPackage
{
    class SubTask<<abstract, RtosTask>> #lightgreen {}

    class ButtonTask #lightgreen {}
    class GpioLedTask #lightgreen {}
    class Max7219Task #lightgreen {}
    class PotmeterTask #lightgreen {}
    class DmxMax3485SenderTask #lightgreen {}

    ButtonTask --|> SubTask
    GpioLedTask --|> SubTask
    Max7219Task ---|> SubTask
    PotmeterTask --|> SubTask
    DmxMax3485SenderTask ---|> SubTask
}

MasterNode "1" *-- "0..*" SubTask
SlaveNode  "1" *-- "0..*" SubTask
MasterTask <-> MasterBridge

MasterNode *--- ServiceTasks
SlaveNode *--- ServiceTasks
SlaveTask <-> SlaveBridge

'Layout

MasterNode_Package -[hidden]-> ServiceTasksPackage

@enduml

@startuml 

@startuml

actor User 

User -> Website : Access website
Website -> WebserverTask: HTTP Request
WebserverTask -> ApiServer: Handle HTTP Request 
ApiServer ->    XXXApi: Handle control API request
XXXApi -> MasterTask: Request action
MasterTask -> MasterBridge: Send message
alt local message, master task
MasterBridge -> MasterTask: Handle message
MasterTask -> MasterBridge: Return result
else local message, service task 
MasterBridge -> ServiceTasks: Handle message
ServiceTasks -> MasterBridge: Return result
else local message, sub task 
MasterBridge -> SubTask: Handle message
SubTask -> MasterBridge: Return result
else remote message
MasterBridge -> SlaveBridge: Send message via ESP-NOW
alt message for slave task
SlaveBridge -> SlaveBridge: Handle message
SlaveTask -> SlaveBridge: Return result
else message for service task
SlaveBridge -> ServiceTasks: Handle message
ServiceTasks -> SlaveBridge: Return result
else message for sub task   
SlaveBridge -> SubTask: Handle message
SubTask -> SlaveBridge: Return result
end
else error message
SlaveBridge -> MasterBridge: Return 
end
MasterBridge -> MasterTask: Return result
MasterTask -> WebserverTask: Return HTTP Response
WebserverTask -> Website: Show

@enduml
